application: petsy-ro
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /api/.*
  script: _go_app

- url: /auth/.*
  script: _go_app

- url: /links/.*
  script: _go_app

- url: /.*
  static_files: static/index.html
  upload: static/index.html